### ISSUE TITLE
(eval):1: command not found: iterm2_prompt_mark in .zsh_custom/powerlevel9k.sh

### ISSUE THREAD

**Issue by creplogle** [connorjs/connorjs#2]
Line 5 of .zsh_custom/powerlevel9k.sh results in the following prompt error:

(eval):1: command not found: iterm2_prompt_mark

**Comment by connorjs** [comment]
I believe this was fixed with df012f81d8535b89ca6dfac0de8dea484252abec; I did that a long while ago, but never pushed it. I'm back online now though, so hopefully that is the fix. If not, please comment on GH-3.
